name: 'Download Buildkite Artifact'
author: 'EnricoMi'
description: 'A GitHub Action to download artifacts from a Buildkite pipeline'
inputs:
  github_token:
    description: 'GitHub API Access Token'
    default: ${{ github.token }}
    required: false
  buildkite_token:
    description: 'Buildkite API Access Token'
    required: true
  buildkite_build_url:
    description: 'Buildkite build url to downloaded artifacts from'
    required: false
  ignore_build_states:
    description: 'List of build states to ignore. No artifacts will be downloaded when build has one of these states. Use comma to separate multiple states, e.g. "canceled,skipped,failed"'
    required: false
    default: ''
  ignore_job_states:
    description: 'List of job states to ignore. No artifacts of jobs that have this state are downloaded. Use comma to separate multiple states, e.g. "timed_out,failed"'
    required: false
    default: ''
  output_path:
    description: 'Path were downloaded artifacts are stored'
    required: false
    default: '.'
  poll_interval:
    description: 'Delay in seconds between polls to the Github and Buildkite APIs'
    required: false
    default: 30
  log_level:
    description: 'Action logging level'
    required: false
    default: 'INFO'
outputs:
  build-number:
    description: 'The number of the Buildkite build'
  build-state:
    description: 'The state of the Buildkite build'
  download-state:
    description: 'The outcome of downloading artifacts: skipped, success, failure'
  download-paths:
    description: 'The paths of downloaded artifacts as a Json array of strings'
  download-files:
    description: 'The number of downloaded files'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/enricomi/download-buildkite-artifact-action:v1.15.0'
branding:
  icon: 'download-cloud'
  color: 'green'
